name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: retr0680/retr0680
          SHOW_TITLE: true
          SECTION_NAME: retr0s-stats
          BLOCKS: █▒
          CODE_LANG: c
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML Markdown
          COMMIT_MESSAGE: Updated Retr0’s Codex with new metrics
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: Retr0
          AUTHOR_EMAIL: dedsecretr0680@gmail.com
